### ISSUE TITLE
Serializing a Python Class Implementing a Java Interface for py4j version 0.8.2.1

### ISSUE THREAD

**Issue by Py4JQuestionAsker** [bartdag/py4j#171]
Hi,

When I try to Serialize an instance of a class implementing Serializable, my code fails because serialization checks are made by using instanceof (see line 1166 of the ObjectOutputStream source code: http://grepcode.com/file/repository.grepcode.com/java/root/jdk/openjdk/6-b14/java/io/ObjectOutputStream.java) and PythonProxyHandler is not an instance of Serializable. A very 
simple example that fails on Pyspark is:
```
class SomeSerializable(object):
    class Java:
        implements = ['java.io.Serializable']
byteStream=sc._jvm.java.io.ByteArrayOutputStream()
objectStream=sc._jvm.java.io.ObjectOutputStream(byteStream)
objectStream.writeObject(SomeSerializable())
```
giving the stack trace

```
Py4JJavaError                             Traceback (most recent call last)
<ipython-input-7-fc2ce1ad2487> in <module>()
----> 1 objectStream.writeObject(a)

/homes/breese/testroot/share/spark/python/lib/py4j-0.8.2.1-src.zip/py4j/java_gateway.py in __call__(self, *args)
    536         answer = self.gateway_client.send_command(command)
    537         return_value = get_return_value(answer, self.gateway_client,
--> 538                 self.target_id, self.name)
    539 
    540         for temp_arg in temp_args:

/homes/breese/testroot/share/spark/python/lib/py4j-0.8.2.1-src.zip/py4j/protocol.py in get_return_value(answer, gateway_client, target_id, name)
    298                 raise Py4JJavaError(
    299                     'An error occurred while calling {0}{1}{2}.\n'.
--> 300                     format(target_id, '.', name), value)
    301             else:
    302                 raise Py4JError(

Py4JJavaError: An error occurred while calling o23.writeObject.
: java.io.NotSerializableException: py4j.reflection.PythonProxyHandler
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1184)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:231)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:379)
	at py4j.Gateway.invoke(Gateway.java:259)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:133)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:207)
	at java.lang.Thread.run(Thread.java:745)
```
My py4j version is 0.8.2.1 and I cannot update because this is the version used by my current version of Apache Spark. I tried sneakily replacing the current version with version 0.9 by renaming a py4j 0.9 zip source and putting it in the python/lib directory, but it is apparently incompatible, and I don't even know if it would work for that version anyway. In any case, I need a workaround so that I can serialize Python classes implementing a Java Interface in py4j 0.8.2.1 on the Java side.

**Comment by JoshRosen** [comment]
@Py4JQuestionAsker, I'd be interested in learning more about the incompatibilities that you ran into while trying to upgrade Spark's Py4J version. There might be broader interest in upgrading Spark's Py4J dependency, so if you're willing to document the problems that you ran into it would be great if you could file a JIRA ticket at https://issues.apache.org/jira/browse/SPARK and link it here.

**Comment by Py4JQuestionAsker** [comment]
It appears I misinterpretted an error iPython gave me which suggested there was an incompatibility, but apparently I zipped the wrong part of the Py4J version. I cannot see any immediate incompatibility issues, but the serialization problem remains.

**Comment by bartdag** [comment]
Hi,

This is a very difficult problem because a PythonProxyHandler (1) holds reference to many complex objects that eventually refer to sockets (not serializable), (2) needs to cleanup itself correctly to free references on the python side.

Can you provide more details about your usage scenario (what are you trying to achieve)?

It's not impossible to implement, just hard and probably application-specific so the best I could do is provide some configuration options/hook to extend PythonProxyHandler and let you implement your own custom serialization methods.

**Comment by Py4JQuestionAsker** [comment]
The end goal is to distribute Python lambda functions to be used like anonymous functions in pre-existing Scala code, though currently the goal is simply to pass an `org.apache.spark.api.java.function.FlatMapFunction`
to a  Java RDD (i.e., PyRDD._jrdd) so that the Python RDD will be deserialized into a Scala RDD that the Scala code may then operate on. While this specific problem is indeed doable by generating more Scala code, the general problem of passing a Python lambda function to Scala is *not*, as least not with what I know about Spark and Py4J. Objects are passed to executors through serialization, so when I try to to wrap a lambda function (or any function really) into an Interface, the executors will attempt to serialize them. All the code *could* exist on the Scala side, but our clients do not want to use Scala, they want to use Python, and hence they will want to pass lambda functions to wrapped Scala classes that we would very much like to not give a complete implementation of in Python. I don't necessarily need them to be serializable, but if not what I do need is a way to send them to the executors *without* serialization. At the moment I am attempting to find a solution using broadcast variables.

**Comment by bartdag** [comment]
If I understand correctly, executors may execute tasks on different processes (or even machines), correct? This is why anything that is sent to an executor must be serialized.

If you want to pass stateless python functions I think I could implement something that does not require object lifecycle management and be of general use for Py4J users. It's still tricky to get it right and efficient.

See this StackOverflow question for a similar situation: http://stackoverflow.com/questions/28006517/redis-on-sparktask-not-serializable

**Comment by Py4JQuestionAsker** [comment]
Yes, though broadcast variables provide a method to share them across machines provided they are read-only. That being said, any official solution offered in Py4J would be much more convenient, it is something I would greatly appreciate.
