### ISSUE TITLE
Error messages are terrible

### ISSUE THREAD

**Issue by aragnon** [bartdag/py4j#181]
I am trying to use PySpark via JupyterHub and all I get from py4j is:
```
ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server
Traceback (most recent call last):
  File "/usr/local/spark/python/lib/py4j-0.8.2.1-src.zip/py4j/java_gateway.py", line 425, in start
    self.socket.connect((self.address, self.port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused
```

"The Java server", as if there is only one running on the system. ROFL.

How about you start outputting something like "We tried to connect to host <hostname>:<port> where we expect that a program <program name> is running"?

**Comment by 243826** [comment]
Thanks. It's fixed in 0.9.1-SNAPSHOT. Awaiting release.

If there are other locations where you would like to have more helpful messages, please suggest  or better yet - send in a pull request.

--
Chetan
