### ISSUE TITLE
py4j.protocol.Py4JNetworkError: An error occurred while trying to connect to the Java server (127.0.0.1:25333)

### ISSUE THREAD

**Issue by zhchen6688** [bartdag/py4j#194]
Env: win7-x64,  Python Version: Python 2.7.10
Java Version : 
java version "1.8.0_45"
Java(TM) SE Runtime Environment (build 1.8.0_45-b15)
Java HotSpot(TM) Client VM (build 25.45-b02, mixed mode)
Py4j Version: py4j 0.9.1 (https://pypi.python.org/packages/source/p/py4j/py4j-0.9.1.tar.gz)

Test Cases Scripts:
>>> from py4j.java_gateway import JavaGateway
>>> gateway = JavaGateway()
>>> random = gateway.jvm.java.util.Random()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "E:\Python27\lib\site-packages\py4j-0.9.1-py2.7.egg\py4j\java_gateway.py", line 120
9, in __getattr__
    "\n" + proto.END_COMMAND_PART)
  File "E:\Python27\lib\site-packages\py4j-0.9.1-py2.7.egg\py4j\java_gateway.py", line 646
, in send_command
    connection = self._get_connection()
  File "E:\Python27\lib\site-packages\py4j-0.9.1-py2.7.egg\py4j\java_gateway.py", line 601
, in _get_connection
    connection = self._create_connection()
  File "E:\Python27\lib\site-packages\py4j-0.9.1-py2.7.egg\py4j\java_gateway.py", line 607
, in _create_connection
    connection.start()
  File "E:\Python27\lib\site-packages\py4j-0.9.1-py2.7.egg\py4j\java_gateway.py", line 719
, in start
    raise Py4JNetworkError(msg, e)
py4j.protocol.Py4JNetworkError: An error occurred while trying to connect to the Java serv
er (127.0.0.1:25333)
>>>

How to resolved this issue?  

My Email:  zhchen6688@126.com

**Comment by bartdag** [comment]
Hi, how is the JVM started?

**Comment by cboratto** [comment]
@bartdag how is the JVM started? Could you provide an example of a simple code?
