### ISSUE TITLE
Broken Pipe

### ISSUE THREAD

**Issue by bafshinpour** [bartdag/py4j#224]
My code seems to work but I also get the following error:

ERROR:py4j.java_gateway:Error while sending or receiving.
Traceback (most recent call last):
  File "/opt/anaconda/lib/python2.7/site-packages/py4j/java_gateway.py", line 762, in send_command
    self.socket.sendall(command.encode("utf-8"))
  File "/opt/anaconda/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 32] Broken pipe

**Comment by bartdag** [comment]
Hi, can you provide more details :

- python, Java, py4j, and OS version 
- code or parameters used to initialize the gateway and gateway server on python and Java side
- more details about the circumstances when this error occurs 

A broken pipe on send is relatively rare : it means that the JVM broke the connection (close, shutdown, process exit) while the Python side is sending a command.

**Comment by bafshinpour** [comment]
The python version: 
2.7.11 | Anaconda
Java:
java version "1.7.0_101"
OpenJDK Runtime Environment (rhel-2.6.6.4.el6_8-x86_64 u101-b00)
OpenJDK 64-Bit Server VM (build 24.95-b01, mixed mode)
OS: Centos 6.7

I know the JVM is running, I launch it as a separate process in another shell, using:
java -Xmx6g -Xms6g  -cp /opt/symetry/lib/sym-assembly.jar com.sml.pyshell.SymetryEntryPoint

**Comment by bartdag** [comment]
Hi, thanks for the info, but I really need more information (code snippets would be great) to be able to help you. 

The most probable cause of this error is that the Java socket is closed. If you use default parameters (infinite read timeout, listening on localhost with regular port) and you do not call close() nor shutdown(), this should never happen. Is this happening always on the same call? Are you sending particularly large parameters when this occurs (e.g., a 1 MB string)?
