### ISSUE TITLE
Can't shutdown jvm correctly

### ISSUE THREAD

**Issue by sho-suzuki** [bartdag/py4j#232]
```
The version of Py4J, Python, and Java are (0.10.1,  3.5.1, openjdk version "1.8.0_91" 64bit)
The OS your are using (centos7)
```

I select data via filemaker jdbc using py4j and, jaydebeapi3.
query to filemaker are run correctly.
However py4j raises an exception error when JVM shutdown.

code as follows,

```py
class DBconnect:
    def _connect_filemaker(self, dbname):
        import jaydebeapi
        cur = ''
        conn = ''
        gateway = ''

        jar = '/usr/local/bin/drivers/fmjdbc.jar'
        # args = '-Djava.class.path={0}'.format(jar)
        driver_class = 'com.filemaker.jdbc.Driver'
        servername = 'hoge.jp:2399'
        account = 'id'
        password = 'pass'
        url = u'jdbc:filemaker://{0}/{1}?user={2}&password={3}'.format(servername, dbname, account, password)
        from py4j import java_gateway
        gateway = java_gateway.JavaGateway()  # jvm
        conn = jaydebeapi.connect(jclassname=driver_class, driver_args=url, jars=jar)  # connnection
        cur = conn.cursor()  # cursor
     return

    def get_record_filemaker(self, dbname):
        rows = []  # result
        cur, conn, gateway = self._connect_filemaker(dbname)  # connection
        sql = 'select * from hoge'
        try:
            cur.execute(sql)  # sql
            rows = cur.fetchall()  # query result
        except:
            print(traceback.format_exc())
        finally:
            self.close_connection(cur, conn, gateway)

    def close_connection(self, cur, conn, gateway=None):
        # close
        cur.close()
        conn.close()
        gateway.shutdown()  # <- error occurs here
        gateway = None
        return
```

client code as follows;

```py
    DB = DBconnect()  # instance
    DB.get_record_filemaker(u'hoge_table')
```

and error is

```py
RROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:25333)
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.5.1/lib/python3.5/site-packages/py4j/java_gateway.py", line 836, in send_command
    raise Py4JError("Answer from Java side is empty")
py4j.protocol.Py4JError: Answer from Java side is empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.pyenv/versions/3.5.1/lib/python3.5/site-packages/py4j/java_gateway.py", line 695, in send_command
    response = connection.send_command(command)
  File "/root/.pyenv/versions/3.5.1/lib/python3.5/site-packages/py4j/java_gateway.py", line 840, in send_command
    raise Py4JNetworkError("Error while sending or receiving", e)
py4j.protocol.Py4JNetworkError: Error while sending or receiving

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.pyenv/versions/3.5.1/lib/python3.5/site-packages/py4j/java_gateway.py", line 638, in _get_connection
    connection = self.deque.pop()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.pyenv/versions/3.5.1/lib/python3.5/site-packages/py4j/java_gateway.py", line 777, in start
    self.socket.connect((self.address, self.port))
ConnectionRefusedError: [Errno 111] Connection refused

... loop many times
```

**Comment by bartdag** [comment]
Hi

Two follow up questions: 

1. Is this an exception that prevents the code from executing after shutdown or are you seeing this in the log output?

2. Can you try 0.10.2.1? I went through the entire network code and made a lot of small fixes. It will be easier to diagnose from the latest release if it does not fix this behaviour.

**Comment by sho-suzuki** [comment]
Hi bartdag

thank you for your quick reply!

1. this exception  prevents the executing code from after shutdown line.
     and It's a stdout log.

2. I upgrade py4j 0.10.1 -> 0.10.2.1. but still occur same error messages.

```py
ERROR:root:Exception while sending command.
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.5.1/lib/python3.5/site-packages/py4j/java_gateway.py", line 928, in send_command
    raise Py4JNetworkError("Answer from Java side is empty")
py4j.protocol.Py4JNetworkError: Answer from Java side is empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.pyenv/versions/3.5.1/lib/python3.5/site-packages/py4j/java_gateway.py", line 778, in send_command
    response = connection.send_command(command)
  File "/root/.pyenv/versions/3.5.1/lib/python3.5/site-packages/py4j/java_gateway.py", line 933, in send_command
    "Error while receiving", e, proto.ERROR_ON_RECEIVE)
py4j.protocol.Py4JNetworkError: Error while receiving
ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:25333)
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.5.1/lib/python3.5/site-packages/py4j/java_gateway.py", line 722, in _get_connection
    connection = self.deque.pop()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.pyenv/versions/3.5.1/lib/python3.5/site-packages/py4j/java_gateway.py", line 857, in start
    self.socket.connect((self.address, self.port))
ConnectionRefusedError: [Errno 111] Connection refused
ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:25333)
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.5.1/lib/python3.5/site-packages/py4j/java_gateway.py", line 722, in _get_connection
    connection = self.deque.pop()
IndexError: pop from an empty deque

... loop many times
```

btw, jaydebeapi3 can't execute after py4j upgrade to 0.10.2.1
because of GatewayConnection() require gateway_parameter.
so I modified `jaydebeapi3/__init__.py`

```diff
def _gateway_is_running():
-    gwconn = java_gateway.GatewayConnection()
+    gwconn = java_gateway.GatewayConnection(java_gateway.GatewayParameters())
```

**Comment by bartdag** [comment]
Hi,

I looked back at the code to make sure, but JavaGateway.shutdown() cannot raise an exception, when raise_exception=False, which is the default value. Exceptions are only logged using logger.info, so if the Python code after gateway.shutdown() does not execute, I'm really confused how this can be possible!

Exceptions do silently occur when shutting down the gateway because there are many states in which the remote and local gateways can be. This is why they are silently logged and the shutdown operation is described as a best effort. Still, I never encountered a situation where shutdown() did not work because of Py4J.

Finally, I would need to take a look at the jaydebeapi3 source code, but instantiating a GatewayConnection is not a supported usage pattern of Py4J. I even deprecated the instantiation of GatewayClient (it is still supported before 1.0, but manually managing GatewayConnection isn't and I don't remember ever supporting this usage pattern). I'll create a ticket to make sure that this is clearly mentioned in the documentation. It's certainly possible that these manually created instances are causing some issues with the shutdown operation.

**Comment by sho-suzuki** [comment]
Hi 
Oh I'm sorry. As you said, also code after the shutdown was able to run.
I would like to lower the level of the logger.
thank you for your help!
