### ISSUE TITLE
Not clear what the problem could be due to masking of the underlying exception

### ISSUE THREAD

**Issue by 243826** [bartdag/py4j#257]
```
py4j.Py4JException: Cannot obtain a new communication channel

at py4j.CallbackClient.sendCommand(CallbackClient.java:251)

at py4j.CallbackClient.sendCommand(CallbackClient.java:259)

at py4j.CallbackClient.sendCommand(CallbackClient.java:228)

at py4j.reflection.PythonProxyHandler.invoke(PythonProxyHandler.java:107)

at com.sun.proxy.$Proxy17.processInput2(Unknown Source)
````

Would be a lot better if the logging actually revealed the underlying reason for "cannot obtain a new communication channel".

**Comment by bartdag** [comment]
Hi,

apologies for the delay. Can you provide more information about how this error?

Usually, errors such as these occur on shutdown (e.g., trying to communicate with the Python side while the Java side is shutting down) and should be captured by the appropriate catch block in the shutdown method.

Additionally, Py4J logs other useful trace using the java.util.logging at the INFO and SEVERE levels.
