### ISSUE TITLE
Error when create python process from Java file

### ISSUE THREAD

**Issue by fredlumm** [bartdag/py4j#286]
Hi,

So I was experiment with the example of "Initiating the communication from the Java side". I try to launch the python process from java file using runtime.exec, and it seems that the process hasn't been launched, and it throws such error:
py4j.Py4JException: Error while obtaining a new communication channel
	at py4j.CallbackClient.getConnectionLock(CallbackClient.java:218)
	at py4j.CallbackClient.sendCommand(CallbackClient.java:337)
	at py4j.CallbackClient.sendCommand(CallbackClient.java:316)
	at py4j.reflection.PythonProxyHandler.invoke(PythonProxyHandler.java:106)
	at com.sun.proxy.$Proxy0.predict(Unknown Source)
	at py4j.examples.ClientServer.main(ClientServer.java:31)
Caused by: java.net.ConnectException: Connection refused
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at java.net.Socket.connect(Socket.java:538)
	at java.net.Socket.<init>(Socket.java:434)
	at java.net.Socket.<init>(Socket.java:244)
	at javax.net.DefaultSocketFactory.createSocket(SocketFactory.java:277)
	at py4j.CallbackConnection.start(CallbackConnection.java:206)
	at py4j.CallbackClient.getConnection(CallbackClient.java:199)
	at py4j.CallbackClient.getConnectionLock(CallbackClient.java:211)
	... 
Anyone can help?

**Comment by fredlumm** [comment]
It seems that i didn't start the python process correctly. After I changed it, everything works fine
