### ISSUE TITLE
Py4JNetworkError: An error occurred while trying to connect to the Java server

### ISSUE THREAD

**Issue by MahanteshAngadiGH** [bartdag/py4j#310]
I am connected to EMR cluster, running the series of pyspark scripts through jupyter from a windows machine. I have ssh the EMR cluster from my windows machine.

I am getting this kind of error, when I am running my pyspark scripts on EMR cluster.

This error comes randomly at any point in the scripts.

What I do is:
1. stop the cluster
2. restart another cluster
3. run all the scripts all over again

With this, I will lose whatever the scripts have successfully completed in the previous run.

Is there a way, I can reconnect back to the java server in the same cluster and continue the execution of the scripts from the point of failure onward without loosing the successfully completed scripts computations/outputs.

Any help will be greatly appreciated.

**Here is complete error trace in the jupyter notebook**

ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:45124)
Traceback (most recent call last):
  File "/usr/lib/spark/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 963, in start
    self.socket.connect((self.address, self.port))
  File "/mnt1/anaconda2/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused
---------------------------------------------------------------------------
Py4JNetworkError                          Traceback (most recent call last)
<ipython-input-204-aa5382ed940d> in <module>()
      1 # ***  This can be removed  ***
----> 2 sparkSession.sql("SELECT * FROM logs_vw").limit(10).toPandas()

/usr/lib/spark/python/pyspark/sql/session.py in sql(self, sqlQuery)
    554         [Row(f1=1, f2=u'row1'), Row(f1=2, f2=u'row2'), Row(f1=3, f2=u'row3')]
    555         """
--> 556         return DataFrame(self._jsparkSession.sql(sqlQuery), self._wrapped)
    557 
    558     @since(2.0)

/usr/lib/spark/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py in __call__(self, *args)
   1129             proto.END_COMMAND_PART
   1130 
-> 1131         answer = self.gateway_client.send_command(command)
   1132         return_value = get_return_value(
   1133             answer, self.gateway_client, self.target_id, self.name)

/usr/lib/spark/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py in send_command(self, command, retry, binary)
    879          if `binary` is `True`.
    880         """
--> 881         connection = self._get_connection()
    882         try:
    883             response = connection.send_command(command)

/usr/lib/spark/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py in _get_connection(self)
    827             connection = self.deque.pop()
    828         except IndexError:
--> 829             connection = self._create_connection()
    830         return connection
    831 

/usr/lib/spark/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py in _create_connection(self)
   833         connection = GatewayConnection(
    834             self.gateway_parameters, self.gateway_property)
--> 835         connection.start()
    836         return connection
    837 

/usr/lib/spark/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py in start(self)
    968                 "server ({0}:{1})".format(self.address, self.port)
    969             logger.exception(msg)
--> 970             raise Py4JNetworkError(msg, e)
    971 
    972     def close(self, reset=False):

Py4JNetworkError: An error occurred while trying to connect to the Java server (127.0.0.1:45124)

**Comment by Aldridgexia** [comment]
same error here, have you found any workaround?

**Comment by johnwallx** [comment]
@MahanteshAngadiGH and @Aldridgexia did you find a workaround for this issue?
