### ISSUE TITLE
Issue - Received Empty Command

### ISSUE THREAD

**Issue by Jaismeen11** [bartdag/py4j#313]
Hi, I am working on a project where multiple java threads are trying to communicate with a python script. I have created a python server like this : 
  gateway = ClientServer(java_parameters=JavaParameters(),python_parameters=PythonParameters(),python_server_entry_point=hello)
    gateway.start_callback_server()

Java : ClientServer server = new ClientServer(null);

Each java thread, then gets the python entry server entrypoint : 
server.getPythonServerEntryPoint(new Class[] { IHello.class });

and invokes the function on the python side.

The calls go through, for example three java calls will invoke the same function on the python side three times, but internally I'm getting the following py4j error. 
Collecting garbage java
Apr 23, 2018 2:49:07 PM py4j.CallbackClient getConnectionLock
INFO: Getting CB Connection
Apr 23, 2018 2:49:07 PM py4j.CallbackClient getConnectionLock
INFO: Acquired CB Connection
Apr 23, 2018 2:49:07 PM py4j.CallbackConnection sendCommand
INFO: Sending CB command: g
t
e

Apr 23, 2018 2:49:07 PM py4j.CallbackConnection sendCommand
INFO: Returning CB command: y
Apr 23, 2018 2:49:07 PM py4j.CallbackClient getConnectionLock
INFO: Getting CB Connection
Apr 23, 2018 2:49:07 PM py4j.CallbackClient getConnectionLock
INFO: Acquired CB Connection
Apr 23, 2018 2:49:07 PM py4j.CallbackConnection sendCommand
INFO: Sending CB command: g
t
e

Apr 23, 2018 2:49:07 PM py4j.CallbackClient sendCommand
WARNING: Error while sending a command
py4j.Py4JNetworkException
	at py4j.CallbackConnection.sendCommand(CallbackConnection.java:138)
	at py4j.CallbackClient.sendCommand(CallbackClient.java:344)
	at py4j.reflection.PythonProxyHandler.finalize(PythonProxyHandler.java:78)
	at java.lang.System$2.invokeFinalize(System.java:1270)
	at java.lang.ref.Finalizer.runFinalizer(Finalizer.java:98)
	at java.lang.ref.Finalizer.access$100(Finalizer.java:34)
	at java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:210)

Apr 23, 2018 2:49:07 PM py4j.CallbackClient sendCommand
SEVERE: Error while sending a command.
py4j.Py4JNetworkException
	at py4j.CallbackConnection.sendCommand(CallbackConnection.java:138)
	at py4j.CallbackClient.sendCommand(CallbackClient.java:344)
	at py4j.reflection.PythonProxyHandler.finalize(PythonProxyHandler.java:78)
	at java.lang.System$2.invokeFinalize(System.java:1270)
	at java.lang.ref.Finalizer.runFinalizer(Finalizer.java:98)
	at java.lang.ref.Finalizer.access$100(Finalizer.java:34)
	at java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:210)

Apr 23, 2018 2:49:07 PM py4j.reflection.PythonProxyHandler finalize
WARNING: Python Proxy ID could not send a finalize message: t
Apr 23, 2018 2:49:07 PM py4j.CallbackClient getConnectionLock
INFO: Getting CB Connection
Apr 23, 2018 2:49:07 PM py4j.CallbackClient getConnectionLock
INFO: Acquired CB Connection
Apr 23, 2018 2:49:07 PM py4j.CallbackConnection sendCommand
INFO: Sending CB command: g
t
e

Apr 23, 2018 2:49:07 PM py4j.CallbackClient sendCommand
WARNING: Error while sending a command
py4j.Py4JNetworkException
	at py4j.CallbackConnection.sendCommand(CallbackConnection.java:138)
	at py4j.CallbackClient.sendCommand(CallbackClient.java:344)
	at py4j.reflection.PythonProxyHandler.finalize(PythonProxyHandler.java:78)
	at java.lang.System$2.invokeFinalize(System.java:1270)
	at java.lang.ref.Finalizer.runFinalizer(Finalizer.java:98)
	at java.lang.ref.Finalizer.access$100(Finalizer.java:34)
	at java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:210)

Apr 23, 2018 2:49:07 PM py4j.CallbackClient sendCommand
SEVERE: Error while sending a command.
py4j.Py4JNetworkException
	at py4j.CallbackConnection.sendCommand(CallbackConnection.java:138)
	at py4j.CallbackClient.sendCommand(CallbackClient.java:344)
	at py4j.reflection.PythonProxyHandler.finalize(PythonProxyHandler.java:78)
	at java.lang.System$2.invokeFinalize(System.java:1270)
	at java.lang.ref.Finalizer.runFinalizer(Finalizer.java:98)
	at java.lang.ref.Finalizer.access$100(Finalizer.java:34)
	at java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:210)

Apr 23, 2018 2:49:07 PM py4j.reflection.PythonProxyHandler finalize
WARNING: Python Proxy ID could not send a finalize message: t

If I want to do some communication again, with same server socket running, I'm unable to do so. I get the following error.

py4j.Py4JException: An exception was raised by the Python Proxy. Return Message: x
at py4j.Protocol.getReturnValue(Protocol.java:434)
at py4j.reflection.PythonProxyHandler.invoke(PythonProxyHandler.java:113)

Can somebody please help?

Thanks,
Jaismeen

**Comment by bartdag** [comment]
Hi,

I regret that I am not logging the exception in the Proxy finalizer on the Java side, it would have been interesting.

Which version of Py4J, Python, and Java are you using? Did you try with one thread instead of three? Did you try with the GatewayServer/JavaGateway classes?

**Comment by daw3rd** [comment]
I'm getting a similar error when using multiple threads (presumably simultaneously active calls through to the same python class).
On the java side

```
$ java -version
openjdk version "11.0.10" 2021-01-19
OpenJDK Runtime Environment (build 11.0.10+9-Ubuntu-0ubuntu1.20.04)
OpenJDK 64-Bit Server VM (build 11.0.10+9-Ubuntu-0ubuntu1.20.04, mixed mode, sharing)
```

with dependency:

```
        <dependency>
            <groupId>net.sf.py4j</groupId>
            <artifactId>py4j</artifactId>
            <version>0.10.8.1</version>
        </dependency>

```
On the python side:

$ pip list | grep py4j
py4j                          0.10.9
$ python --version
Python 3.8.5
```


py4j.Py4JException: Error while sending a command.
	at py4j.CallbackClient.sendCommand(CallbackClient.java:397)
	at py4j.CallbackClient.sendCommand(CallbackClient.java:356)
	at py4j.reflection.PythonProxyHandler.invoke(PythonProxyHandler.java:106)
	at com.sun.proxy.$Proxy6.classify(Unknown Source)
	at com.ibm.watson.iot.sound.modeling.python.PythonClassifierBridge.classify(PythonClassifierBridge.java:378)
	at com.ibm.watson.iot.sound.modeling.python.FixedPythonClassifier.classify(FixedPythonClassifier.java:168)
	at com.ibm.watson.iot.sound.modeling.AbstractFixedFeatureExtractingClassifier.classify(AbstractFixedFeatureExtractingClassifier.java:99)
	at com.ibm.watson.iot.sound.modeling.AbstractFixableClassifier.classify(AbstractFixableClassifier.java:125)
	at com.ibm.watson.iot.sound.SoundTestUtils.verifyClassification(SoundTestUtils.java:536)
	at com.ibm.watson.iot.sound.SoundTestUtils.verifyClassifications(SoundTestUtils.java:497)
	at com.ibm.watson.iot.sound.modeling.AbstractMulticlassClassifierTest.testTrainClassifySignalSeparation(AbstractMulticlassClassifierTest.java:453)
	at com.ibm.watson.iot.sound.modeling.AbstractMulticlassClassifierTest.testMixedDurations(AbstractMulticlassClassifierTest.java:416)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:89)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:41)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:542)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:770)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:464)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)
Caused by: py4j.Py4JNetworkException: Error while sending a command: c
t
classify
ao25
e

	at py4j.ClientServerConnection.sendCommand(ClientServerConnection.java:253)
	at py4j.CallbackClient.sendCommand(CallbackClient.java:384)
	... 35 more
Caused by: py4j.Py4JException: Received empty command
	at py4j.ClientServerConnection.sendCommand(ClientServerConnection.java:236)
	... 36 more
```
