### ISSUE TITLE
ValueError: invalid literal for int()

### ISSUE THREAD

**Issue by uanlgex** [bartdag/py4j#334]
Hi.
I'm calling a java method returning a double, but py4j tries to cast it to an int returning the above mentioned error. Any idea ?
Thanks

Environment : 
Python 3.6.4 |Anaconda, Inc.| (default, Jan 16 2018, 10:22:32) [MSC v.1900 64 bit (AMD64)]
Java 1.8.0_111-b14

Traceback (most recent call last):

  File "<ipython-input-6-1d98c0db0657>", line 29, in <module>
    print(h.getNumeric(1).doubleValue())

  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\py4j\java_gateway.py", line 1257, in __call__
    answer, self.gateway_client, self.target_id, self.name)

  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\py4j\protocol.py", line 342, in get_return_value
    return OUTPUT_CONVERTER[type](answer[2:], gateway_client)

  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\py4j\protocol.py", line 164, in <lambda>
    INTEGER_TYPE: (lambda value, y: int(value)),

ValueError: invalid literal for int() with base 10: '648239.61'

**Comment by bartdag** [comment]
Sorry for the long long long delay. Can you post some code snippets (Java and Python) to make it easier to reproduce the problem.

Py4J tries to be smart when automatically casting primitives or finding the right type conversion/overriden method, but at its heart, this can be an undecidable problem depending on the context.
