### ISSUE TITLE
Invalid Interface name when packaged jar is used as a plugin

### ISSUE THREAD

**Issue by bryantChhun** [bartdag/py4j#339]
If i copy the example from ["implementing java interface from python"](https://www.py4j.org/advanced_topics.html#implementing-java-interfaces-from-python-callback), package to a jar, then run that jar, the program runs fine and can find the interface name.  However, if I run the jar as a plugin in my parent program, it fails with the following error:

```
Py4JError: An error occurred while calling o0.registerListener. Trace:
py4j.Py4JException: Invalid interface name: ExampleListener
    at py4j.Protocol.getPythonProxy(Protocol.java:429)
    at py4j.Protocol.getObject(Protocol.java:311)
    at py4j.commands.AbstractCommand.getArguments(AbstractCommand.java:82)
    at py4j.commands.CallCommand.execute(CallCommand.java:77)
    at py4j.GatewayConnection.run(GatewayConnection.java:238)
    at java.lang.Thread.run(Thread.java:748)
```

The parent program looks for the following code in the jar to identify plugins.  When the user selects the plugin from a drop down menu ("onPluginSelected"), it launches py4j and the ListenerApplication.

```
import org.micromanager.MenuPlugin;
import org.scijava.plugin.Plugin;
import org.scijava.plugin.SciJavaPlugin;
import py4j.GatewayServer;

@Plugin(type = MenuPlugin.class)
public class Py4JPluginInterface implements MenuPlugin, SciJavaPlugin{
     ...
    @Override
    public String getSubMenu() {
        return "Simpletest_gradle";
    }

    @Override
    public void onPluginSelected() {
        GatewayServer gatewayServer = new GatewayServer(new ListenerApplication());
        gatewayServer.start();
    }
```

Interesting thing is, I can add a method to inspect the interface like such:
```
public String classTest() throws Exception {
    Class<?> py = Class.forName("ExampleListener");
    return py.toString();
}
```
Which returns:
`'interface ExampleListener'`

So I think the program can see the interface just fine!

I have a suspicion that this bug is something really stupid ... Any help is greatly appreciated :-)

**Comment by bartdag** [comment]
Hi, can you provide more information about the plugin system you are using? Is this an Eclipse application?

One reason the python may not be able to find the interface is because of classloading issues, which is common when using plugin/osgi systems (e.g., each plugin has its own classloader).

You can take a look at setClassLoadingStrategy https://www.py4j.org/_static/javadoc/py4j/reflection/ReflectionUtil.html#setClassLoadingStrategy-py4j.reflection.ClassLoadingStrategy-

and ClassLoadingStrategy (https://www.py4j.org/_static/javadoc/py4j/reflection/ClassLoadingStrategy.html). My guess would be that RootClassLoadingStrategy might help (the default class loading strategy is current thread).

**Comment by bryantChhun** [comment]
Hi bartdag,

This is a plugin for this application: 
https://micro-manager.org/wiki/Writing_plugins_for_Micro-Manager

The program uses JRE 1.6, but i've been using 1.8.  This could be the big problem?  Even if I force the program to run on 1.8 (it seems to function fine), there still seems to be a classloading issue

I'll give your methods a try.  Is it possible to set a classloading strategy and reload plugin classes after the core program launches?  This plugin should not depend on changes to the core program.

**Comment by bryantChhun** [comment]
Hi bartadg,

I finally got around to using py4j's classloading strategy.  It works!

Thanks for all your help.
