### ISSUE TITLE
py4j exception

### ISSUE THREAD

**Issue by gayatrivenugopal** [bartdag/py4j#343]
I have installed Java 11 and Python 3 on CentOS. Trying to run a code that worked perfectly fine on a Windows environment. Getting this exception:
ERROR:root:Exception while sending command.
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/py4j/java_gateway.py", line 1188, in send_command
    raise Py4JNetworkError("Answer from Java side is empty")
py4j.protocol.Py4JNetworkError: Answer from Java side is empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/py4j/java_gateway.py", line 1014, in send_command
    response = connection.send_command(command)
  File "/usr/lib/python3.4/site-packages/py4j/java_gateway.py", line 1193, in send_command
    "Error while receiving", e, proto.ERROR_ON_RECEIVE)
py4j.protocol.Py4JNetworkError: Error while receiving
Traceback (most recent call last):
  File "WordInformation.py", line 493, in <module>
    status = read_from_source("../Corpora/Bhandarkar Oriental Research Books")
  File "WordInformation.py", line 473, in read_from_source
    author, year)
  File "WordInformation.py", line 381, in fetch_from_hwn
    return read_store_properties(word, file, sentence, source, category, author, year);
  File "WordInformation.py", line 79, in read_store_properties
    properties["synsets"] = get_other_props(word)
  File "WordInformation.py", line 226, in get_other_props
    output = gateway.jvm.Properties.getProperties(word)
  File "/usr/lib/python3.4/site-packages/py4j/java_gateway.py", line 1286, in __call__
    answer, self.gateway_client, self.target_id, self.name)
  File "/usr/lib/python3.4/site-packages/py4j/protocol.py", line 336, in get_return_value
    format(target_id, ".", name))
py4j.protocol.Py4JError: An error occurred while calling z:in.ac.iitb.cfilt.jhwnl.examples.Properties.getProperties

Is this because of some dependency? I have set the JAVA_HOME and updated the PATH variable.

**Comment by bartdag** [comment]
Hi,
 
Can you describe how the python code is executed (e.g., in a virtual environment)? launch_gateway tries to be smart at finding the right jar file and java executable, but it may fail depending on the python environment.

Can you also check that:

1. There is no other JVM running when you start your program.
2. There is indeed a JVM started after the gateway = JavaGateway(...) line. You can either add a sleep and check with a process monitoring tool (top, htop, ps aux) or run it interactively in a python shell.
3. Can you call simple functions such as gateway.jvm.currentTimeMillis() ?
