### ISSUE TITLE
GatewayServer shutting down

### ISSUE THREAD

**Issue by wesleyw72** [bartdag/py4j#346]
We are noticing a problem where occasionally the GatewayServer seems to shut down for no apparent reason. There are no exceptions produced, we just get an error much like the one below when calling a Java method through Py4J.

The Python process is still running healthily. I've tried enabling the logging options in Py4J but that doesn't produce any more information.

There doesn't seem to be a deterministic way of reproducing this issue. However, it does seem to only happen when using Python interactively. 

Do you have any idea what could be causing this or how we could further debug it?

```
ERROR:root:Exception while sending command.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/py4j/java_gateway.py", line 1188, in send_command
    raise Py4JNetworkError("Answer from Java side is empty")
py4j.protocol.Py4JNetworkError: Answer from Java side is empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/py4j/java_gateway.py", line 1014, in send_command
    response = connection.send_command(command)
  File "/usr/local/lib/python3.7/site-packages/py4j/java_gateway.py", line 1193, in send_command
    "Error while receiving", e, proto.ERROR_ON_RECEIVE)
py4j.protocol.Py4JNetworkError: Error while receiving
ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:55501)
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/py4j/java_gateway.py", line 958, in _get_connection
    connection = self.deque.pop()
IndexError: pop from an empty deque
```

**Comment by bartdag** [comment]
Hi,

I am not aware of such problem, but I would first make 100% sure that the GatewayServer is indeed shut down and instrument the Java side first (enable logging, register a GatewayServerListener, try to directly connect with the GatewayServer socket, is the JVM still up & running? etc.). 

The two common scenarios I've encountered in the past is (1) the GatewayServer or even the entire JVM being closed by user code and (2) a shutdown command sent from the Python side, again by user code.

Also, which version of Py4J, Python, Java, and OS are you using?

**Comment by wesleyw72** [comment]
I think we have found the cause. Users were pressing Ctrl+C and therefore sending a SIGINT to the Java process. I notice there is a flag `create_new_process_group` which can be set on the gateway, however that seems to imply that rogue Java processes could be left if the python process is killed in some cases.

It seems PySpark does some [stuff](https://github.com/apache/spark/blob/71170e74df5c7ec657f61154212d1dc2ba7d0613/python/pyspark/java_gateway.py#L78) to get around this. 

Ctrl+C is quite commonly pressed by users using Python interactively to clear what they have typed. Is there another flag that can be set to handle these better. If not, would it be something that may be on the feature roadmap for the future?

Thanks for all your work on Py4J!
