### ISSUE TITLE
auto_convert=True not working in ClientServer

### ISSUE THREAD

**Issue by daw3rd** [bartdag/py4j#359]
I am trying to return a python list of dictionaries to a java List of Maps.  It seems I need to do conversion and I can get the proper operation when doing the following:

```python
    def classify(self, data):
        print('classify')
        classification = {}
        classification['name'] = 'labelname'
        classification['value'] = 'labelvalue'
        classification['confidence'] = 1.0
        classification = MapConverter().convert(classification, gateway._gateway_client)
        clist = []
        clist.append(classification)
        clist = ListConverter().convert(clist, gateway._gateway_client)
        return clist
```

I would like to not require the explicit conversion using MapConverter and ListConverter.  So, I changed the starting of the ClientServer to the following to turn on autoconvert:

```python
    gateway = ClientServer(
        java_parameters=JavaParameters(auto_convert=True),
        python_parameters=PythonParameters(),
        python_server_entry_point=python_classifier)
```

But this results in the following (w/o the explicit conversions)

```
Exception in thread "main" py4j.Py4JException: An exception was raised by the Python Proxy. Return Message: Traceback (most recent call last):
  File "C:\dev\Python36\lib\site-packages\py4j\clientserver.py", line 583, in _call_proxy
    get_command_part(return_value, self.pool)
  File "C:\dev\Python36\lib\site-packages\py4j\protocol.py", line 298, in get_command_part
    command_part = REFERENCE_TYPE + parameter._get_object_id()
AttributeError: 'list' object has no attribute '_get_object_id'
```

So it seems the auto_convert is not actually taking effect?

Using py4j 0.10.8.1 in Python 3.6. and 0.10.8.1 in JVM maven dependency.

Thanks in advance - David

**Comment by bartdag** [comment]
Hi, I will need a more complete code example to help on this one because auto_convert does work for clientserver:

```python
from py4j.clientserver import ClientServer, JavaParameters, PythonParameters
clientserver = ClientServer(java_parameters=JavaParameters(auto_convert=True))
# Will print [1, 2, 3]. If the Python list was not converted, an exception would be raised.
clientserver.jvm.System.out.println([1, 2, 3])
```

**Comment by antoine-guillou** [comment]
Hi,
I got the same issue when trying to return a List<Integer> from a CallBack.
I followed this [example ](https://www.py4j.org/advanced_topics.html#implementing-java-interfaces-from-python-callback), replaced the returned Object by a List<Integer> and added the auto_convert = True in the JavaGateway creation.

gateway.jvm.System.out.println([1, 2, 3]) in the same method works fine.

**Comment by antoine-guillou** [comment]
Added this bit of code in CallbackConnection _call_proxy made the trick:
            
           return_value = getattr(self.pool[obj_id], method)(*params)

            if not isinstance(return_value, JavaObject):
                for converter in self.gateway_client.converters:
                    if converter.can_convert(return_value):
                        return_value = converter.convert(return_value, self.gateway_client)
                        break

            return proto.RETURN_MESSAGE + proto.SUCCESS +\
                get_command_part(return_value, self.pool)

**Comment by codeflush-dev** [comment]
Faced this issue too, can build a workaround though but would be nice if it gets fixed

**Comment by chernias** [comment]
@antoine-guillou Hey. Do you plan to create a PR to the main repo?
Looks like it's still reproducible, and your fix is working when applied manually.
