### ISSUE TITLE
Python client can't communicate with Java gateway server in docker containers

### ISSUE THREAD

**Issue by vshivam** [bartdag/py4j#360]
I have two docker containers running. One of them contains the python code and the other starts the java gateway server. When trying to communicate from the python container to the java container, an exception is thrown. Seems like the two containers are not able to communicate over sockets. Is it possible to fix this somehow ?

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/py4j/java_gateway.py", line 958, in _get_connection
    connection = self.deque.pop()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/py4j/java_gateway.py", line 1096, in start
    self.socket.connect((self.address, self.port))
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/py4j/java_gateway.py", line 1284, in __call__
    answer = self.gateway_client.send_command(command)
  File "/usr/local/lib/python3.6/site-packages/py4j/java_gateway.py", line 1012, in send_command
    connection = self._get_connection()
  File "/usr/local/lib/python3.6/site-packages/py4j/java_gateway.py", line 960, in _get_connection
    connection = self._create_connection()
  File "/usr/local/lib/python3.6/site-packages/py4j/java_gateway.py", line 966, in _create_connection
    connection.start()
  File "/usr/local/lib/python3.6/site-packages/py4j/java_gateway.py", line 1108, in start
    raise Py4JNetworkError(msg, e)
py4j.protocol.Py4JNetworkError: An error occurred while trying to connect to the Java server (wiktionary:25333)
```

**Comment by peidong-hu** [comment]
I solved it by using IPv4address explicitly when create Gateway server on java side.

**Comment by Vonisoa** [comment]
Can you show an example please on how you did it?

**Comment by peidong-hu** [comment]
App app = new App();
            InetAddress addr;
            System.setProperty("java.net.preferIPv4Stack", "true");
            addr = Inet4Address.getByName("0.0.0.0");
            GatewayServerBuilder builder = new GatewayServer.GatewayServerBuilder(
                    app);
            builder.javaAddress(addr);
            GatewayServer server = builder.build();
            server.start();

**Comment by Vonisoa** [comment]
Thank you

**Comment by meenraj** [comment]
It works with the solution provided by @peidong-hu

**Comment by codework247** [comment]
Hello @peidong-hu,
I tried your approach what you suggeseted above. But still getting the error. Do you have any other solution to resolve this issue ?

**Comment by codework247** [comment]
even changing the default ports w.r.t Gateway server is not letting me connect from Python side.

**Comment by anmolbhatia05** [comment]
@codework247 If you could solve your error, can you please share your python code ? Or maybe @peidong-hu you can ?
