### ISSUE TITLE
"Answer from Java side is empty" when passing a Map to python

### ISSUE THREAD

**Issue by sylvain-mazet** [bartdag/py4j#361]
Hi all,
could not find answer to this, so here it is:
I am trying a simple call from java to python through py4j.

What  I have in mind:
- I want a python "server" receiving requests from a JVM.
- The JVM could be brought down, I would like the python "server" to remain.
- When a new JVM is fired up, it should call the python server, just the same.

I have an error I dont understand in the code below.
I fire up the python server.
I fire up the JVM, all is fine.
When the JVM is fired up the second time and calls python, I get the error below.

Any help appreciated.
System configuration:
py4j: 0.10.8.1
java: 1.8
python: 3.7.3
on linux mint 17.3 Rosa, based on ubuntu 14.04.4

Sylvain Mazet.

```
Traceback (most recent call last):
  File "..../lib/python3.7/site-packages/py4j/java_gateway.py", line 1188, in send_command
    raise Py4JNetworkError("Answer from Java side is empty")
py4j.protocol.Py4JNetworkError: Answer from Java side is empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "..../lib/python3.7/site-packages/py4j/java_gateway.py", line 1014, in send_command
    response = connection.send_command(command)
  File "..../lib/python3.7/site-packages/py4j/java_gateway.py", line 1193, in send_command
    "Error while receiving", e, proto.ERROR_ON_RECEIVE)
py4j.protocol.Py4JNetworkError: Error while receiving
ERROR:py4j.java_gateway:There was an exception while executing the Python Proxy on the Python Side.
Traceback (most recent call last):
  File "..../lib/python3.7/site-packages/py4j/java_gateway.py", line 2410, in _call_proxy
    return_value = getattr(self.pool[obj_id], method)(*params)
  File "/data/smazet/dev/tests/pyserver.py", line 10, in tryPassingAMap
    obj1 = args['first']
  File "..../lib/python3.7/site-packages/py4j/java_collections.py", line 69, in __getitem__
    return self._get(key)
  File "..../lib/python3.7/site-packages/py4j/java_gateway.py", line 1286, in __call__
    answer, self.gateway_client, self.target_id, self.name)
  File "..../lib/python3.7/site-packages/py4j/protocol.py", line 336, in get_return_value
    format(target_id, ".", name))
py4j.protocol.Py4JError: An error occurred while calling o0.get
```

cat pyserver.py
```
from py4j.java_gateway import JavaGateway, CallbackServerParameters

class FirstService(object):
    def __init__(self):
        pass

    def tryPassingAMap(self, args):
        print ("Reception on")
        obj1 = args["first"]
        obj2 = args["second"]
        print ("Hello, got args 1 %s (%s) , %s (%s)" %(obj1,
                                                         obj1.__class__,
                                                         obj2,
                                                         obj2.__class__))
        return "Got your map"

    def hello(self):
        print ("Received greetings")
        return "Hi yourself"

    def tryPassingAList(self,all):
        print ("received a list")
        for obj in all:
            if type(obj) == str:
                print ("   it is a string : %s" %(obj))
            else:
                print ("Type : %s" %type(obj))

        return "Got your list"

    class Java:
        implements = ["com.softbridge.tests.utils.PythonInterfaceAPI"]

if __name__== "__main__":
    firstService = FirstService()
    gateway = JavaGateway(
        callback_server_parameters=CallbackServerParameters(daemonize=False, daemonize_connections=False),
        python_server_entry_point=firstService
    )
    print ("Service started")
```

cat TestServer.py
```
package com.softbridge.standalone.testpy4j;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import py4j.ClientServer;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * Created by smazet on 11/06/19.
 */
public class TestServer {

    public static final Logger logger = LoggerFactory.getLogger(TestServer.class);

    public static void main(String[] args) throws Exception {
        ClientServer clientServer = new ClientServer(null);
        PythonInterfaceAPI pyAPI = (PythonInterfaceAPI) clientServer.getPythonServerEntryPoint(new Class[] {PythonInterfaceAPI.class});

        try {
            Map<String,Object> hashmap = new HashMap<String,Object>();
            hashmap.put("first", "{'id': 'ererer'}");
            hashmap.put("second", "another string");
            String result = pyAPI.tryPassingAMap(hashmap);
            logger.info("Response from Python: "+result);
        } catch (Exception e) {
            logger.error("Error while passing a map");
            e.printStackTrace();
        }

        try {
            List<Object> strings = new ArrayList<Object>();
            strings.add("do");
            strings.add("you");
            strings.add("copy?");
            String result2 = pyAPI.tryPassingAList(strings);
            logger.info("Response from list Python: "+result2);
        } catch (Exception e) {
            logger.error("Error while passing a list");
            e.printStackTrace();
        }

        try {
            String response = pyAPI.hello();
            logger.info("I've been polite to python: "+response);
        } catch (Exception e) {
            logger.error("Error while passing nothing");
            e.printStackTrace();
        }

        clientServer.shutdown();
    }
}
```

**Comment by phillipcheng** [comment]
same question, any discovery since then.
