### ISSUE TITLE
"TypeError: 'NoneType' object is not callable" from _garbage_collect_object on process exit

### ISSUE THREAD

**Issue by torokati44** [bartdag/py4j#383]
I kept getting a similar error on process cleanup to what's described in #106, but from a different location:

```
Exception ignored in: <function JavaObject.__init__.<locals>.<lambda> at 0x7f643623d7a0>
Traceback (most recent call last):
  File "py4j/java_gateway.py", line 1294, in <lambda>
  File "py4j/java_gateway.py", line 629, in _garbage_collect_object
  File "/usr/lib64/python3.7/logging/__init__.py", line 1365, in debug
  File "/usr/lib64/python3.7/logging/__init__.py", line 1621, in isEnabledFor
TypeError: 'NoneType' object is not callable
Exception ignored in: <function JavaObject.__init__.<locals>.<lambda> at 0x7f6433b6a320>
Traceback (most recent call last):
  File "py4j/java_gateway.py", line 1294, in <lambda>
  File "py4j/java_gateway.py", line 629, in _garbage_collect_object
  File "/usr/lib64/python3.7/logging/__init__.py", line 1365, in debug
  File "/usr/lib64/python3.7/logging/__init__.py", line 1621, in isEnabledFor
TypeError: 'NoneType' object is not callable
```

The strange thing is that on that particular line in `logging/__init__.py`, the object which is `None` is the ` _acquireLock` global function. I think somehow the `logging` module got cleaned up before `java_gateway`.

Adding this extra check to `_garbage_collect_object` got rid of the error messages for me:

```
    except Exception:
        if logging.debug: # <--
            logger.debug("Exception while garbage collecting an object",
                     exc_info=True)
```

**Comment by bartdag** [comment]
Hi, which version of Py4J are you using?

The current version has this check, which should catch the error you are referring to:

```python
def _garbage_collect_object(gateway_client, target_id):
    try:
        try:
            ThreadSafeFinalizer.remove_finalizer(
                smart_decode(gateway_client.address) +
                smart_decode(gateway_client.port) +
                target_id)
            gateway_client.garbage_collect_object(target_id)
        except Exception:
            logger.debug(
                "Exception while garbage collecting an object",
                exc_info=True)
    except Exception:
        # Maybe logger is dead at this point.
        pass
```

https://github.com/bartdag/py4j/blob/master/py4j-python/src/py4j/java_gateway.py#L644

**Comment by torokati44** [comment]
The exception comes from this line:
https://github.com/bartdag/py4j/blob/a17131353cf5ed0b41aa004d4ae6ae516c695c88/py4j-python/src/py4j/java_gateway.py#L646
There is no check in place before that for whether `logger` is `None` or not.

**Comment by torokati44** [comment]
But actually, I think we are no longer triggering this bug, even without my "fix". So from my part, you can close this issue if you don't want to deal with it.
