### ISSUE TITLE
Could not find py4j jar

### ISSUE THREAD

**Issue by lakshman-1396** [bartdag/py4j#392]
>>> model = Model.fromFile("dec_tree.xml")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/METNET/skulkarni21/pypmml/pypmml/model.py", line 152, in fromFile
    pc = PMMLContext.getOrCreate()
  File "/home/METNET/skulkarni21/pypmml/pypmml/base.py", line 77, in getOrCreate
    PMMLContext()
  File "/home/METNET/skulkarni21/pypmml/pypmml/base.py", line 51, in __init__
    PMMLContext._ensure_initialized(self, gateway=gateway)
  File "/home/METNET/skulkarni21/pypmml/pypmml/base.py", line 60, in _ensure_initialized
    PMMLContext._gateway = gateway or cls.launch_gateway()
  File "/home/METNET/skulkarni21/pypmml/pypmml/base.py", line 86, in launch_gateway
    _port = launch_gateway(classpath=launch_classpath, die_on_exit=True)
  File "/usr/hdp/2.6.5.0-292/spark2/python/lib/py4j-0.10.6-src.zip/py4j/java_gateway.py", line 281, in launch_gateway
py4j.protocol.Py4JError: Could not find py4j jar at

**Comment by lakshman-1396** [comment]
I resolved the issue by pointing the jarfile to the path where i had the py4j jar.
