### ISSUE TITLE
Scala class does not exist in the JVM

### ISSUE THREAD

**Issue by JWDobken** [bartdag/py4j#404]
I have a locally built JAR file of [Deequ](https://github.com/awslabs/deequ) (which is a Scala project) that I can access from the Scala Repl:

``` cmd
$ scala -cp deequ-1.1.0-SNAPSHOT.jar
Welcome to Scala 2.13.3 (OpenJDK 64-Bit Server VM, Java 1.8.0_242).
Type in expressions for evaluation. Or try :help.
scala> import com.amazon.deequ.VerificationSuite
import com.amazon.deequ.VerificationSuite
scala> var vs=VerificationSuite()
var vs: com.amazon.deequ.VerificationSuite = com.amazon.deequ.VerificationSuite@7187bac9
```

To make the JAR library available to Python I pass the jarfile as `classpath` to Py4J's `launch_gateway` :

``` python
from pathlib import Path
from py4j.java_gateway import JavaGateway, launch_gateway, GatewayParameters, CallbackServerParameters
jarfile = Path('deequ-1.1.0-SNAPSHOT.jar').absolute().as_posix()

port = launch_gateway(classpath=jarfile)
gateway = JavaGateway(
    gateway_parameters=GatewayParameters(port=port),
    callback_server_parameters=CallbackServerParameters(port=0)
)

random = gateway.jvm.java.util.Random() 

number1 = random.nextInt(10)
number2 = random.nextInt(10)
print(number1,number2)
```

> 3 1

Now if I call the `VerificationSuite` :

``` python
>> gateway.jvm.com.amazon.deequ.VerificationSuite
ERROR:root:Exception while sending command.
Traceback (most recent call last):
  File "/Users/USERNAME/miniconda3/lib/python3.7/site-packages/py4j/java_gateway.py", line 1159, in send_command
    raise Py4JNetworkError("Answer from Java side is empty")
py4j.protocol.Py4JNetworkError: Answer from Java side is empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/USERNAME/miniconda3/lib/python3.7/site-packages/py4j/java_gateway.py", line 985, in send_command
    response = connection.send_command(command)
  File "/Users/USERNAME/miniconda3/lib/python3.7/site-packages/py4j/java_gateway.py", line 1164, in send_command
    "Error while receiving", e, proto.ERROR_ON_RECEIVE)
py4j.protocol.Py4JNetworkError: Error while receiving

---------------------------------------------------------------------------
Py4JError                                 Traceback (most recent call last)
<ipython-input-25-83e646b43b32> in <module>
----> 1 gateway.jvm.com.amazon.deequ.VerificationSuite

~/miniconda3/lib/python3.7/site-packages/py4j/java_gateway.py in __getattr__(self, name)
   1596                 answer[proto.CLASS_FQN_START:], self._gateway_client)
   1597         else:
-> 1598             raise Py4JError("{0} does not exist in the JVM".format(new_fqn))
   1599 
   1600 

Py4JError: com.amazon.deequ.VerificationSuite does not exist in the JVM
```

When I mistype the class name, there is no error and the result is of type `<py4j.java_gateway.JavaPackage at 0x112786090>` . It looks like the path to the class is recognized but not as a proper class?

* Python 3.7
* py4j version 0.10.7

**Comment by katharine-fuzesi** [comment]
I am facing the same issue. Any updates on this?
