### ISSUE TITLE
ValueError: invalid literal for int() with base 10: b''

### ISSUE THREAD

**Issue by windyoung** [bartdag/py4j#407]
debug log showing 
2020-09-15 08:03:32,000 - java_gateway(300) - launch_gateway - DEBUG- Launching gateway with command ['java', '-classpath', 'C:\\Program Files\\Python37\\share/py4j/py4j0.10.8.1.jar;ocs;ocs', 'D:\\Projects\\OCM\\ocm_py\\libs\\qmdbjdbc-9.0.3-mdb.jar', 'py4j.GatewayServer', '--die-on-broken-pipe', '25333']
Traceback (most recent call last):
  File "d:/Projects/OCM/ocm_py/DBcon_odbc.py", line 66, in <module>
    qmdb_odbc()
  File "d:/Projects/OCM/ocm_py/DBcon_odbc.py", line 57, in qmdb_odbc
    conn = jaydebeapi.connect(dirver, url, [user, password], jarFile)
  File "C:\Program Files\Python37\lib\site-packages\jaydebeapi\__init__.py", line 63, in connect
    port=25333, classpath=classpath, javaopts=javaopts, die_on_exit=True)
  File "C:\Program Files\Python37\lib\site-packages\py4j\java_gateway.py", line 2113, in launch_gateway
    enable_auth=enable_auth)
  File "C:\Program Files\Python37\lib\site-packages\py4j\java_gateway.py", line 327, in launch_gateway
    _port = int(proc.stdout.readline())
ValueError: invalid literal for int() with base 10: b''

I tryed with py4j version 0.10.8.1,0.10.9.1,0.10.9  showing the the same error 
python 3.7.9 , java 1.8 , 64 bit 
launch_gateway.py code line 
    # Determine which port the server started on (needed to support
    # ephemeral ports)
    _port = int(proc.stdout.readline())

**Comment by windyoung** [comment]
tcping.exe 127.0.0.1 25333

Probing 127.0.0.1:25333/tcp - No response - time=2001.354ms
Probing 127.0.0.1:25333/tcp - No response - time=2001.131ms
Probing 127.0.0.1:25333/tcp - No response - time=2000.178ms
Probing 127.0.0.1:25333/tcp - No response - time=684.187ms
Ping statistics for 127.0.0.1:25333
     4 probes sent.
     0 successful, 4 failed.  (100.00% fail)
Was unable to connect, cannot provide trip statistics.

**Comment by windyoung** [comment]
may related  wtih  https://github.com/hiddenswitch/Spellsource/issues/740
