### ISSUE TITLE
ArrayIndexOutOfBoundsException: -1 when running ArrayList.clear()

### ISSUE THREAD

**Issue by johann-petrak** [bartdag/py4j#417]
Using py4j version 0.10.9.1 on Ubuntu Linux with ObenJDK Java 1.8.0_252-b09

```
l1 = gateway.jvm.java.util.ArrayList()
l1.clear()
```

Produces the exception shown below. What I find strange is that it looks as if the array would get cleared
at the Python side by repeatedly invoking pop() instead of just actually calling the java method clear() which should be much faster. 
Is there a way to avoid this and just call the java method?

```
---------------------------------------------------------------------------
Py4JJavaError                             Traceback (most recent call last)
<ipython-input-9-8cbfeda56ff8> in <module>
----> 1 l1.clear()

~/software/anaconda/envs/gatenlp-36/lib/python3.6/_collections_abc.py in clear(self)
    975         try:
    976             while True:
--> 977                 self.pop()
    978         except IndexError:
    979             pass

~/software/anaconda/envs/gatenlp-36/lib/python3.6/site-packages/py4j/java_collections.py in pop(self, key)
    443         else:
    444             new_key = self.__compute_index(key)
--> 445         return self.java_remove(new_key)
    446 
    447     def index(self, value):

~/software/anaconda/envs/gatenlp-36/lib/python3.6/site-packages/py4j/java_gateway.py in __call__(self, *args)
   1303         answer = self.gateway_client.send_command(command)
   1304         return_value = get_return_value(
-> 1305             answer, self.gateway_client, self.target_id, self.name)
   1306 
   1307         for temp_arg in temp_args:

~/software/anaconda/envs/gatenlp-36/lib/python3.6/site-packages/py4j/protocol.py in get_return_value(answer, gateway_client, target_id, name)
    326                 raise Py4JJavaError(
    327                     "An error occurred while calling {0}{1}{2}.\n".
--> 328                     format(target_id, ".", name), value)
    329             else:
    330                 raise Py4JError(

Py4JJavaError: An error occurred while calling o0.remove.
: java.lang.ArrayIndexOutOfBoundsException: -1
	at java.util.ArrayList.elementData(ArrayList.java:422)
	at java.util.ArrayList.remove(ArrayList.java:499)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by bartdag** [comment]
Hi, I believe you are using auto_convert=True and the Python implementation of clear() calls pop() and expects an IndexError when the list is empty.

The JavaList.pop method implementation should probably look like:

```python
    def pop(self, key=None):
        if key is None:
            size = self.size()
            if size == 0:
                raise IndexError("list index out of range")
            else:
                new_key = size - 1
        else:
            new_key = self.__compute_index(key)
        return self.java_remove(new_key)
```

instead of the current implementation:

```python
    def pop(self, key=None):
        if key is None:
            new_key = self.size() - 1
        else:
            new_key = self.__compute_index(key)
        return self.java_remove(new_key)
```

A pull request with the relevant test would ensure that this bug is fixed sooner than later :-)

**Comment by johann-petrak** [comment]
Hmm, when I check `gateway.gateway_parameters.auto_convert` it is False but `type(l1)` is `py4j.java_collections.JavaList` 

The proposed code above would now raise the Exception on the Python side when running clear, I think.
It seems the problem here is that the Python somecollection.clear() method is implemented by using pop() until the collection throws an index error exception. This is not the right way to do this for the Java List though, so I think it would be better to instead explicitly implement the clear method in JavaList and handle that explicitly.
