### ISSUE TITLE
ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:39593)

### ISSUE THREAD

**Issue by nabanitapaul1** [bartdag/py4j#425]
I am getting the following error. can any one help me to solve the issue

spark= sparknlp.start()

ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:39593)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/py4j/java_gateway.py", line 929, in _get_connection
    connection = self.deque.pop()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/py4j/java_gateway.py", line 1067, in start
    self.socket.connect((self.address, self.port))
ConnectionRefusedError: [Errno 111] Connection refused
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/py4j/java_gateway.py in _get_connection(self)
    928         try:
--> 929             connection = self.deque.pop()
    930         except IndexError:

IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

ConnectionRefusedError                    Traceback (most recent call last)
8 frames
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Py4JNetworkError                          Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/py4j/java_gateway.py in start(self)
   1077                 "server ({0}:{1})".format(self.address, self.port)
   1078             logger.exception(msg)
-> 1079             raise Py4JNetworkError(msg, e)
   1080 
   1081     def _authenticate_connection(self):

Py4JNetworkError: An error occurred while trying to connect to the Java server (127.0.0.1:39593)

**Comment by niroshank** [comment]
Did you get fix this?

**Comment by felix-hilden** [comment]
It seems pretty obscure, but here to voice my support. This happens in PyFlink 1.17.1 on Python 3.9 in Docker too, inconsistently but happens. It seems the issue might be resource-related or fixed by a restart ([SO](https://stackoverflow.com/questions/51359802/pyspark-errorpy4j-java-gatewayan-error-occurred-while-trying-to-connect-to-the)) I will dig deeper and report results if I have any.

In the meantime, is there anything on the py4j side that could make the error message better? Why would this line fail?
