### ISSUE TITLE
Py4j Connection raise error when using tls for a lot times of invocation BUG.

### ISSUE THREAD

**Issue by fmzone** [bartdag/py4j#429]
client_ssl_context = ssl.SSLContext(ssl.PROTOCOL_TLSv1_2)
    client_ssl_context.verify_mode = ssl.CERT_REQUIRED
    client_ssl_context.set_ciphers(
        "ECDHE-RSA-AES256-GCM-SHA384:AES256-GCM-SHA384:DHE-RSA-AES256-GCM-SHA384:"
        "ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256")
    client_ssl_context.load_verify_locations(cafile=config_utils.get_crt_path())
    client_ssl_context.options |= (ssl.OP_NO_SSLv2 | ssl.OP_NO_SSLv3 | ssl.OP_NO_TLSv1 | ssl.OP_NO_TLSv1_1)
    return client_ssl_context

param = GatewayParameters(port=int(py4j_port), address=py4j_addr, ssl_context=ssl_context,
                                  auth_token=config_utils.obtain_auth_token())
gate_way = JavaGateway(gateway_parameters=param)

****when use tls to encrypt connection the following error raised,it work at first but when it keep working for some times the it will raise the error .when i set param ssl_context to None it work fine  .**** 

Traceback (most recent call last):
  Inspect\tools\py4j\java_gateway.py", line 982, in _get_connection
    connection = self.deque.pop()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Oracle ToolKit\tools\Inspect\tools\py4j\java_gateway.py", line 1120, in start
    self.socket.connect((self.address, self.port))
  File "ssl.py", line 1342, in connect
  File "ssl.py", line 1333, in _real_connect
  File "ssl.py", line 1309, in do_handshake
ssl.SSLError: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1123)

**Comment by fmzone** [comment]
sorry it's caused by my code in java when it run for sometime the java code change the ciper suit then the connection work error
