### ISSUE TITLE
Java Gateway does not log through logger

### ISSUE THREAD

**Issue by dcontador** [bartdag/py4j#457]
Some Java Gateway messages are logged using the `logging` module directly, hence those messages ignore logging level set for `py4j`.

Particularly happens when any Python script using Spark (2.4.7 in Windows) closes, provoking one or more exceptions that cannot be hidden configuring the `py4j` logger:

> 
> ERROR:root:Exception while sending command.
> Traceback (most recent call last):
>   File "C:\CESADAR\ATAVIA\PYTHON\lib\site-packages\py4j\java_gateway.py", line 1152, in send_command
>     answer = smart_decode(self.stream.readline()[:-1])
>   File "C:\CESADAR\ATAVIA\PYTHON\lib\socket.py", line 589, in readinto
>     return self._sock.recv_into(b)
> ConnectionResetError: [WinError 10054] Se ha forzado la interrupción de una conexión existente por el host remoto
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "C:\CESADAR\ATAVIA\PYTHON\lib\site-packages\py4j\java_gateway.py", line 985, in send_command
>     response = connection.send_command(command)
>   File "C:\CESADAR\ATAVIA\PYTHON\lib\site-packages\py4j\java_gateway.py", line 1164, in send_command
>     "Error while receiving", e, proto.ERROR_ON_RECEIVE)
> py4j.protocol.Py4JNetworkError: Error while receiving
>

**Comment by max-espinoza-mil** [comment]
Can we get this fixed?

**Comment by Lodewic** [comment]
OP created a PR here: https://github.com/dcontador/py4j/pull/1
But not to the official py4j, only his own fork. 

I also hope this can be fixed, would the PR be sufficient if it were pointed to the actual py4j repository?

---
In databricks I need to silence to `root` logger to avoid these logs. Instead, I just want to configure the py4j logging level to silence these messages and do whatever I want with the root logger.

**Comment by nkpopov** [comment]
Ended up here for the same reason .. can't silence these exceptions from the root logger in Databricks (listing below). Wanted to create an issue and file PR with the fix, but found this issue and PR with correct fix. Could this PR be landed to the master?
```
2025-05-01 18:43:20,785 INFO java_gateway.py:1052 Exception while sending command.
Traceback (most recent call last):
  File "/databricks/spark/python/lib/py4j-0.10.9.7-src.zip/py4j/clientserver.py", line 528, in send_command
    self.socket.sendall(command.encode("utf-8"))
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/databricks/spark/python/lib/py4j-0.10.9.7-src.zip/py4j/java_gateway.py", line 1038, in send_command
    response = connection.send_command(command)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/databricks/spark/python/lib/py4j-0.10.9.7-src.zip/py4j/clientserver.py", line 531, in send_command
    raise Py4JNetworkError(
py4j.protocol.Py4JNetworkError: Error while sending
```

**Comment by b0uks** [comment]
Hi, I've found adding filters to the python logging module to be effective in silencing these error messages.

utilizing this class, i've been able to suppress these  messages


```
    class SuppressPy4JConnectionReset(logging.Filter):
        def filter(self, record):
            # Check if the message contains the target string
            if record.name != "root":
                return True
            if record.levelno != logging.INFO:
                return True
            if "Exception while sending command." not in record.getMessage():
                return True
            return False

    logging.getLogger().addFilter(SuppressPy4JConnectionReset())

```
